name: Check file size
on:
  # push:
  #   branches:
  #     - gradio
  workflow_dispatch:

jobs:
  check-file-size:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check large files
        uses: ActionsDesk/lfs-warning@v2.0
        with:
          filesizelimit: 10485760 # this is 10MB so we can sync to HF Spaces
