name: Update deployment files on gradio branch

on:
  push:
    branches:
      - main
    paths:
      - "deployment/**"
      - "models/**/*.pth"
      - ".github/workflows/**"
      - ".github/actions/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_deployment_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          lfs: true

      - name: Build deployment folder
        run: |
          mkdir -p temp
          cp -r deployment/* temp
          cp models/vit_saved.pth temp
          cp -r .git temp/
          cp -r .github temp/
          cp .gitattributes temp
          cp LICENSE temp

      - name: Update gradio branch
        run: |
          git config --global user.email "javier@carnero.net"
          git config --global user.name "Javier Carnero"
          git fetch
          git checkout gradio
          echo "--------"
          git branch -a
          echo "--------"
          git remote show origin
          echo "--------"
          echo "--------"
          find . -mindepth 1 ! -regex '^./temp\(/.*\)?' -delete
          cp -r temp/. .
          rm -rf temp
          sed -i 's/\.\.\/models\/vit_saved\.pth/\.\/vit_saved\.pth/g' app.py
          git add -A .
          git diff-index --quiet gradio || git commit -m "Copy deployment files to gradio branch"
          echo "--------"
          git branch -a
          echo "--------"
          git remote show origin
          echo "--------"
          echo "--------"
          git push origin gradio
