name: Copy deployment files to gradio branch

on:
  push:
    branches:
      - main
    paths:
      - "deployment/**"
      - "models/**/*.pth"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  copy_deployment_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          lfs: true

      - name: Update deployment files
        run: |
          mkdir -p temp
          cp -r deployment/* temp
          cp models/vit_saved.pth temp
          cp .gitattributes temp
          git fetch
          git checkout gradio
          shopt -s extglob
          rm -rf !(temp|*/.git)
          cp -r temp/* .
          rm -rf temp
          sed -i 's/\.\.\/models\/vit_saved\.pth/\.\/vit_saved\.pth/g' app.py

      - name: Push deployment files to gradio branch
        run: |
          git config --global user.email "javier@carnero.net"
          git config --global user.name "Javier Carnero"
          git add .
          git diff-index --quiet HEAD || git commit -m "Copy deployment files to gradio branch"
          git push origin gradio
