name: Copy deployment files to gradio branch

on:
  push:
    branches:
      - main

jobs:
  copy_deployment_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Update files in gradio branch
        run: |
          mkdir -p temp
          cp -r deployment/* temp
          cp models/vit_saved.pth temp
          cp .gitattributes temp
          git checkout gradio
          find . -not -path "./temp/*" -delete
          cp -r temp/* .
          rm -rf temp
          sed -i 's/\.\.\/models\/vit_saved\.pth/vit_saved\.pth/g' app.py

      - name: Setup Git
        run: |
          git config --global user.email "javier@carnero.net"
          git config --global user.name "Javier Carnero"

      - name: Push to gradio branch
        run: |
          git add .
          git commit -m "Copy deployment files to gradio branch"
          git push origin gradio
