name: Publish to Hugging Face

on:
  push:
    branches:
      - gradio

jobs:
  publish_to_huggingface:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: gradio

      - name: Checkout hugging face
        uses: actions/checkout@v3
        with:
          repository: https://huggingface.co/spaces/jcarnero/birds-classifier
          token: ${{ secrets.HF_TOKEN }}
          path: hf-repo

      - name: Clean previous Hugging Face repository content
        run: |
          shopt -s extglob
          cd hf-repo
          rm -rf !(.git)

      - name: Setup Git
        run: |
          git config --global user.email "javier@carnero.net"
          git config --global user.name "Javier Carnero"

      - name: Publish gradio to Hugging Face repository
        run: |
          cp -r ${{ github.workspace }}/* hf-repo/
          cd hf-repo/
          git add .
          git commit -m "Publish gradio branch from ${{ github.repository }}/${{ github.ref }} (${{ github.sha }})"
          git push origin main
